export const hrrs = [
    {value:'0',label: 'Abvaluejan - GMT 0', gmt:'0'},
    {value:'1',label: 'Acra - GMT 0', gmt:'0'},
    {value:'2',label: 'Adelavaluee - GMT 9.3', gmt:'9.3'},
    {value:'3',label: 'Áden - GMT 3', gmt:'3'},
    {value:'4',label: 'Adis Abeba - GMT 3', gmt:'3'},
    {value:'5',label: 'Almaty - GMT 6', gmt:'6'},
    {value:'6',label: 'Amã - GMT 3', gmt:'3'},
    {value:'7',label: 'Amesterdão - GMT 2', gmt:'2'},
    {value:'8',label: 'Anadyr - GMT 12', gmt:'12'},
    {value:'9',label: 'Anchorage - GMT -8', gmt:'-8'},
    {value:'10',label: 'Antananarivo - GMT 3', gmt:'3'},
    {value:'11',label: 'Araguaina - GMT -3', gmt:'-3'},
    {value:'12',label: 'Argel - GMT 1', gmt:'1'},
    {value:'13',label: 'Asgabate - GMT 5', gmt:'5'},
    {value:'14',label: 'Asmara - GMT 3', gmt:'3'},
    {value:'15',label: 'Assunção - GMT -4', gmt:'-4'},
    {value:'16',label: 'Astracã - GMT 4', gmt:'4'},
    {value:'17',label: 'Atenas - GMT 3', gmt:'3'},
    {value:'18',label: 'Atikokan - GMT -5', gmt:'-5'},
    {value:'19',label: 'Atyrau - GMT 5', gmt:'5'},
    {value:'20',label: 'Auckland - GMT 12', gmt:'12'},
    {value:'21',label: 'Bacu - GMT 4', gmt:'4'},
    {value:'22',label: 'Bagdá - GMT 3', gmt:'3'},
    {value:'23',label: 'Bamako - GMT 0', gmt:'0'},
    {value:'24',label: 'Bancoque - GMT 7', gmt:'7'},
    {value:'25',label: 'Bangui - GMT 1', gmt:'1'},
    {value:'26',label: 'Banjul - GMT 0', gmt:'0'},
    {value:'27',label: 'Barnaul - GMT 7', gmt:'7'},
    {value:'28',label: 'Beirute - GMT 3', gmt:'3'},
    {value:'29',label: 'Belém - GMT -3', gmt:'-3'},
    {value:'30',label: 'Belgrado - GMT 2', gmt:'2'},
    {value:'31',label: 'Belize - GMT -6', gmt:'-6'},
    {value:'32',label: 'Berlim - GMT 2', gmt:'2'},
    {value:'33',label: 'Beulah - GMT -5', gmt:'-5'},
    {value:'34',label: 'Bisqueque - GMT 6', gmt:'6'},
    {value:'35',label: 'Bissau - GMT 0', gmt:'0'},
    {value:'36',label: 'Blantyre - GMT 2', gmt:'2'},
    {value:'37',label: 'Boa Vista - GMT -4', gmt:'-4'},
    {value:'38',label: 'Bogotá - GMT -5', gmt:'-5'},
    {value:'39',label: 'Boise - GMT -6', gmt:'-6'},
    {value:'40',label: 'Brasília - GMT -3', gmt:'-3'},
    {value:'41',label: 'Bratislava - GMT 2', gmt:'2'},
    {value:'42',label: 'Brazzaville - GMT 1', gmt:'1'},
    {value:'43',label: 'Brisbane - GMT 10', gmt:'10'},
    {value:'44',label: 'Broken Hill - GMT 9.30', gmt:'9.30'},
    {value:'45',label: 'Bruxelas - GMT 2', gmt:'2'},
    {value:'46',label: 'Bucareste - GMT 3', gmt:'3'},
    {value:'47',label: 'Budapeste - GMT 2', gmt:'2'},
    {value:'48',label: 'Buenos Aires - GMT -3', gmt:'-3'},
    {value:'49',label: 'Bujumbura - GMT 2', gmt:'2'},
    {value:'50',label: 'Büsingen - GMT 2', gmt:'2'},
    {value:'51',label: 'Cabul - GMT 4.30', gmt:'4.30'},
    {value:'52',label: 'Caiena - GMT -3', gmt:'-3'},
    {value:'53',label: 'Cairo - GMT 2', gmt:'2'},
    {value:'54',label: 'Calcutá - GMT 5.30', gmt:'5.30'},
    {value:'55',label: 'Caliningrado - GMT 2', gmt:'2'},
    {value:'56',label: 'Campo Grande - GMT -4', gmt:'-4'},
    {value:'57',label: 'Cancún - GMT -5', gmt:'-5'},
    {value:'58',label: 'Caracas - GMT -4', gmt:'-4'},
    {value:'59',label: 'Carachi - GMT 5', gmt:'5'},
    {value:'60',label: 'Cartum - GMT 2', gmt:'2'},
    {value:'61',label: 'Casablanca - GMT 1', gmt:'1'},
    {value:'62',label: 'Catmandu - GMT 5.45', gmt:'5.45'},
    {value:'63',label: 'Center - GMT -5', gmt:'-5'},
    {value:'64',label: 'Ceuta - GMT 2', gmt:'2'},
    {value:'65',label: 'Chicago - GMT -5', gmt:'-5'},
    {value:'66',label: 'Chihuahua - GMT -6', gmt:'-6'},
    {value:'67',label: 'Chişinău - GMT 3', gmt:'3'},
    {value:'68',label: 'Chita - GMT 9', gmt:'9'},
    {value:'69',label: 'Choibalsan - GMT 8', gmt:'8'},
    {value:'70',label: 'Cvalueade da Guatemala - GMT -6', gmt:'-6'},
    {value:'71',label: 'Cvalueade do México - GMT -5', gmt:'-5'},
    {value:'72',label: 'Colombo - GMT 5.30', gmt:'5.30'},
    {value:'73',label: 'Conacri - GMT 0', gmt:'0'},
    {value:'74',label: 'Copenhaga - GMT 2', gmt:'2'},
    {value:'75',label: 'Córdova - GMT -3', gmt:'-3'},
    {value:'76',label: 'Creston - GMT -7', gmt:'-7'},
    {value:'77',label: 'Cuiabá - GMT -4', gmt:'-4'},
    {value:'78',label: 'Currie - GMT 10', gmt:'10'},
    {value:'79',label: 'Daca - GMT 6', gmt:'6'},
    {value:'80',label: 'Dacar - GMT 0', gmt:'0'},
    {value:'81',label: 'Damasco - GMT 3', gmt:'3'},
    {value:'82',label: 'Darwin - GMT 9.30', gmt:'9.30'},
    {value:'83',label: 'Dawson - GMT -7', gmt:'-7'},
    {value:'84',label: 'Dawson Creek - GMT -7', gmt:'-7'},
    {value:'85',label: 'Denver - GMT -6', gmt:'-6'},
    {value:'86',label: 'Detroit - GMT -4', gmt:'-4'},
    {value:'87',label: 'Díli - GMT 9', gmt:'9'},
    {value:'88',label: 'Djibouti - GMT 3', gmt:'3'},
    {value:'89',label: 'Douala - GMT 1', gmt:'1'},
    {value:'90',label: 'Dubai - GMT 4', gmt:'4'},
    {value:'91',label: 'Dublin - GMT 1', gmt:'1'},
    {value:'92',label: 'Dushanbe - GMT 5', gmt:'5'},
    {value:'93',label: 'Edmonton - GMT -6', gmt:'-6'},
    {value:'94',label: 'Eirunepe - GMT -5', gmt:'-5'},
    {value:'95',label: 'Escópia - GMT 2', gmt:'2'},
    {value:'96',label: 'Estação McMurdo - GMT 12', gmt:'12'},
    {value:'97',label: 'Estocolmo - GMT 2', gmt:'2'},
    {value:'98',label: 'Famagusta - GMT 3', gmt:'3'},
    {value:'99',label: 'Fort Nelson - GMT -7', gmt:'-7'},
    {value:'100',label: 'Fortaleza - GMT -3', gmt:'-3'},
    {value:'101',label: 'Freetown - GMT 0', gmt:'0'},
    {value:'102',label: 'Gaborone - GMT 2', gmt:'2'},
    {value:'103',label: 'Gaza - GMT 3', gmt:'3'},
    {value:'104',label: 'Glace Bay - GMT -3', gmt:'-3'},
    {value:'105',label: 'Guaiaquil - GMT -5', gmt:'-5'},
    {value:'106',label: 'Halifax - GMT -3', gmt:'-3'},
    {value:'107',label: 'Harare - GMT 2', gmt:'2'},
    {value:'108',label: 'Havana - GMT -4', gmt:'-4'},
    {value:'109',label: 'Hebrom - GMT 3', gmt:'3'},
    {value:'110',label: 'Helsínquia - GMT 3', gmt:'3'},
    {value:'111',label: 'Hermosillo - GMT -7', gmt:'-7'},
    {value:'112',label: 'Hobart - GMT 10', gmt:'10'},
    {value:'113',label: 'Honolulu - GMT -10', gmt:'-10'},
    {value:'114',label: 'Indianápolis - GMT -4', gmt:'-4'},
    {value:'115',label: 'Inuvik - GMT -6', gmt:'-6'},
    {value:'116',label: 'Iqaluit - GMT -4', gmt:'-4'},
    {value:'117',label: 'Irkutsk - GMT 8', gmt:'8'},
    {value:'118',label: 'Istambul - GMT 3', gmt:'3'},
    {value:'119',label: 'Jakarta - GMT 7', gmt:'7'},
    {value:'120',label: 'Jayapura - GMT 9', gmt:'9'},
    {value:'121',label: 'Jerusalém - GMT 3', gmt:'3'},
    {value:'122',label: 'Johannesburgo - GMT 2', gmt:'2'},
    {value:'123',label: 'Juba - GMT 2', gmt:'2'},
    {value:'124',label: 'Juneau - GMT -8', gmt:'-8'},
    {value:'125',label: 'Kampala - GMT 3', gmt:'3'},
    {value:'126',label: 'Kigali - GMT 2', gmt:'2'},
    {value:'127',label: 'Kirov - GMT 3', gmt:'3'},
    {value:'128',label: 'Knox - GMT -5', gmt:'-5'},
    {value:'129',label: 'Krasnoyarsk - GMT 7', gmt:'7'},
    {value:'130',label: 'Kuala Lumpur - GMT 8', gmt:'8'},
    {value:'131',label: 'Kuching - GMT 8', gmt:'8'},
    {value:'132',label: 'Kuwait - GMT 3', gmt:'3'},
    {value:'133',label: 'La Paz - GMT -4', gmt:'-4'},
    {value:'134',label: 'Lagos - GMT 1', gmt:'1'},
    {value:'135',label: 'Libreville - GMT 1', gmt:'1'},
    {value:'136',label: 'Lima - GMT -5', gmt:'-5'},
    {value:'137',label: 'Lisboa - GMT 1', gmt:'1'},
    {value:'138',label: 'Liubliana - GMT 2', gmt:'2'},
    {value:'139',label: 'Lomé - GMT 0', gmt:'0'},
    {value:'140',label: 'Londres - GMT 1', gmt:'1'},
    {value:'141',label: 'Los Angeles - GMT -7', gmt:'-7'},
    {value:'142',label: 'Louisville - GMT -4', gmt:'-4'},
    {value:'143',label: 'Luanda - GMT 1', gmt:'1'},
    {value:'144',label: 'Lubumbashi - GMT 2', gmt:'2'},
    {value:'145',label: 'Lusaka - GMT 2', gmt:'2'},
    {value:'146',label: 'Luxemburgo - GMT 2', gmt:'2'},
    {value:'147',label: 'Macassar - GMT 8', gmt:'8'},
    {value:'148',label: 'Maceió - GMT -3', gmt:'-3'},
    {value:'149',label: 'Madrvalue - GMT 2', gmt:'2'},
    {value:'150',label: 'Magadan - GMT 11', gmt:'11'},
    {value:'151',label: 'Malabo - GMT 1', gmt:'1'},
    {value:'152',label: 'Manágua - GMT -6', gmt:'-6'},
    {value:'153',label: 'Manaus - GMT -4', gmt:'-4'},
    {value:'154',label: 'Manila - GMT 8', gmt:'8'},
    {value:'155',label: 'Maputo - GMT 2', gmt:'2'},
    {value:'156',label: 'Marengo - GMT -4', gmt:'-4'},
    {value:'157',label: 'Mascate - GMT 4', gmt:'4'},
    {value:'158',label: 'Maseru - GMT 2', gmt:'2'},
    {value:'159',label: 'Mazatlán - GMT -6', gmt:'-6'},
    {value:'160',label: 'Mbabane - GMT 2', gmt:'2'},
    {value:'161',label: 'Melbourne - GMT 10', gmt:'10'},
    {value:'162',label: 'Mendoza - GMT -3', gmt:'-3'},
    {value:'163',label: 'Menominee - GMT -5', gmt:'-5'},
    {value:'164',label: 'Mervaluea - GMT -5', gmt:'-5'},
    {value:'165',label: 'Metlakatla - GMT -8', gmt:'-8'},
    {value:'166',label: 'Minsk - GMT 3', gmt:'3'},
    {value:'167',label: 'Mogadíscio - GMT 3', gmt:'3'},
    {value:'168',label: 'Moncton - GMT -3', gmt:'-3'},
    {value:'169',label: 'Monróvia - GMT 0', gmt:'0'},
    {value:'170',label: 'Monterrey - GMT -5', gmt:'-5'},
    {value:'171',label: 'Montevvalueéu - GMT -3', gmt:'-3'},
    {value:'172',label: 'Monticello - GMT -4', gmt:'-4'},
    {value:'173',label: 'Moscou - GMT 3', gmt:'3'},
    {value:'174',label: 'Nairóbi - GMT 3', gmt:'3'},
    {value:'175',label: 'Nassau - GMT -4', gmt:'-4'},
    {value:'176',label: 'New Salem - GMT -5', gmt:'-5'},
    {value:'177',label: 'Niamey - GMT 1', gmt:'1'},
    {value:'178',label: 'Nicósia - GMT 3', gmt:'3'},
    {value:'179',label: 'Nome - GMT -8', gmt:'-8'},
    {value:'180',label: 'Nouakchott - GMT 0', gmt:'0'},
    {value:'181',label: 'Nouméa - GMT 11', gmt:'11'},
    {value:'182',label: 'Nova Iorque - GMT -4', gmt:'-4'},
    {value:'183',label: 'Novokuznetsk - GMT 7', gmt:'7'},
    {value:'184',label: 'Novosibirsk - GMT 7', gmt:'7'},
    {value:'185',label: 'Ojinaga - GMT -6', gmt:'-6'},
    {value:'186',label: 'Omsk - GMT 6', gmt:'6'},
    {value:'187',label: 'Oral - GMT 5', gmt:'5'},
    {value:'188',label: 'Oslo - GMT 2', gmt:'2'},
    {value:'189',label: 'Ouagadougou - GMT 0', gmt:'0'},
    {value:'190',label: 'Panamá - GMT -5', gmt:'-5'},
    {value:'191',label: 'Pangnirtung - GMT -4', gmt:'-4'},
    {value:'192',label: 'Paramaribo - GMT -3', gmt:'-3'},
    {value:'193',label: 'Paris - GMT 2', gmt:'2'},
    {value:'194',label: 'Perth - GMT 8', gmt:'8'},
    {value:'195',label: 'Petersburg - GMT -4', gmt:'-4'},
    {value:'196',label: 'Phoenix - GMT -7', gmt:'-7'},
    {value:'197',label: 'Pionguiangue - GMT 9', gmt:'9'},
    {value:'198',label: 'Pnom Pene - GMT 7', gmt:'7'},
    {value:'199',label: 'Podgorica - GMT 2', gmt:'2'},
    {value:'200',label: 'Pontianak - GMT 7', gmt:'7'},
    {value:'201',label: 'Port Moresby - GMT 10', gmt:'10'},
    {value:'202',label: 'Port Stanley - GMT -3', gmt:'-3'},
    {value:'203',label: 'Porto Príncipe - GMT -4', gmt:'-4'},
    {value:'204',label: 'Porto Velho - GMT -4', gmt:'-4'},
    {value:'205',label: 'Porto-Novo - GMT 1', gmt:'1'},
    {value:'206',label: 'Praga - GMT 2', gmt:'2'},
    {value:'207',label: 'Punta Arenas - GMT -3', gmt:'-3'},
    {value:'208',label: 'Quinxassa - GMT 1', gmt:'1'},
    {value:'209',label: 'Rangum - GMT 5.30', gmt:'5.30'},
    {value:'210',label: 'Rankin Inlet - GMT -5', gmt:'-5'},
    {value:'211',label: 'Recife - GMT -3', gmt:'-3'},
    {value:'212',label: 'Regina - GMT -6', gmt:'-6'},
    {value:'213',label: 'Reiquiavique - GMT 0', gmt:'0'},
    {value:'214',label: 'Riade - GMT 3', gmt:'3'},
    {value:'215',label: 'Riga - GMT 3', gmt:'3'},
    {value:'216',label: 'Rio Branco - GMT -5', gmt:'-5'},
    {value:'217',label: 'Río Gallegos - GMT -3', gmt:'-3'},
    {value:'218',label: 'Rioja - GMT -3', gmt:'-3'},
    {value:'219',label: 'Roma - GMT 2', gmt:'2'},
    {value:'220',label: 'Salta - GMT -3', gmt:'-3'},
    {value:'221',label: 'Samara - GMT 4', gmt:'4'},
    {value:'222',label: 'Samarcanda - GMT 5', gmt:'5'},
    {value:'223',label: 'San Juan - GMT -3', gmt:'-3'},
    {value:'224',label: 'San Luis - GMT -3', gmt:'-3'},
    {value:'225',label: 'Santarém - GMT -3', gmt:'-3'},
    {value:'226',label: 'Santiago do Chile - GMT -3', gmt:'-3'},
    {value:'227',label: 'Santo Domingo - GMT -4', gmt:'-4'},
    {value:'228',label: 'São Paulo - GMT -3', gmt:'-3'},
    {value:'229',label: 'Sarajevo - GMT 2', gmt:'2'},
    {value:'230',label: 'Saratov - GMT 4', gmt:'4'},
    {value:'231',label: 'Seul - GMT 9', gmt:'9'},
    {value:'232',label: 'Simferopol - GMT 3', gmt:'3'},
    {value:'233',label: 'Sitka - GMT -8', gmt:'-8'},
    {value:'234',label: 'Sófia - GMT 3', gmt:'3'},
    {value:'235',label: 'Swift Current - GMT -6', gmt:'-6'},
    {value:'236',label: 'Sydney - GMT 10', gmt:'10'},
    {value:'237',label: 'Taipé - GMT 8', gmt:'8'},
    {value:'238',label: 'Tallinn - GMT 3', gmt:'3'},
    {value:'239',label: 'Tashkent - GMT 5', gmt:'5'},
    {value:'240',label: 'Teerã - GMT 5.30', gmt:'5.30'},
    {value:'241',label: 'Tegucigalpa - GMT -6', gmt:'-6'},
    {value:'242',label: 'Tell City - GMT -5', gmt:'-5'},
    {value:'243',label: 'Thimbu - GMT 6', gmt:'6'},
    {value:'244',label: 'Thunder Bay - GMT -4', gmt:'-4'},
    {value:'245',label: 'Tiblíssi - GMT 4', gmt:'4'},
    {value:'246',label: 'Tijuana - GMT -7', gmt:'-7'},
    {value:'247',label: 'Tomsk - GMT 7', gmt:'7'},
    {value:'248',label: 'Tóquio - GMT 9', gmt:'9'},
    {value:'249',label: 'Toronto - GMT -4', gmt:'-4'},
    {value:'250',label: 'Trípoli - GMT 2', gmt:'2'},
    {value:'251',label: 'Tunes - GMT 1', gmt:'1'},
    {value:'252',label: 'Ulianovsk - GMT 4', gmt:'4'},
    {value:'253',label: 'Urumqi - GMT 6', gmt:'6'},
    {value:'254',label: 'Ushuaia - GMT -3', gmt:'-3'},
    {value:'255',label: 'Uzhhorod - GMT 3', gmt:'3'},
    {value:'256',label: 'Vancôver - GMT -7', gmt:'-7'},
    {value:'257',label: 'Varsóvia - GMT 2', gmt:'2'},
    {value:'258',label: 'Vevay - GMT -4', gmt:'-4'},
    {value:'259',label: 'Viena - GMT 2', gmt:'2'},
    {value:'260',label: 'Vienciana - GMT 7', gmt:'7'},
    {value:'261',label: 'Vilnius - GMT 3', gmt:'3'},
    {value:'262',label: 'Vincennes - GMT -4', gmt:'-4'},
    {value:'263',label: 'Vinduque - GMT 2', gmt:'2'},
    {value:'264',label: 'Vladivostok - GMT 10', gmt:'10'},
    {value:'265',label: 'Volgogrado - GMT 3', gmt:'3'},
    {value:'266',label: 'Whitehorse - GMT -7', gmt:'-7'},
    {value:'267',label: 'Winamac - GMT -4', gmt:'-4'},
    {value:'268',label: 'Winnipeg - GMT -5', gmt:'-5'},
    {value:'269',label: 'Xangai - GMT 8', gmt:'8'},
    {value:'270',label: 'Yakutat - GMT -8', gmt:'-8'},
    {value:'271',label: 'Yakutsk - GMT 9', gmt:'9'},
    {value:'272',label: 'Yekaterinburg - GMT 5', gmt:'5'},
    {value:'273',label: 'Yellowknife - GMT -6', gmt:'-6'},
    {value:'274',label: 'Yerevan - GMT 4', gmt:'4'},
    {value:'275',label: 'Zagreb - GMT 2', gmt:'2'},
    {value:'276',label: 'Zurique - GMT 2', gmt:'2'},
    
]    